import os
import django
from datetime import date
from django.utils.translation import gettext as _

# Configuration de Django
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'multilang_site.settings')
django.setup()

# Import du modèle Article
from main.models import Article

def add_articles(language_code):
    # Définir la langue pour la traduction
    from django.utils.translation import activate
    activate(language_code)

    article1 = Article(
        title='How to Improve Your Productivity in 5 Simple Steps',
        content='In a rapidly evolving world, maximizing your productivity is essential for success. Whether you are a seasoned professional or an ambitious student, optimizing your efficiency can transform your daily life and help you achieve your goals faster. To do this, it is crucial to plan your day with precision. Establish a clear and realistic list of tasks each day, prioritizing activities based on their importance and urgency. Using time management tools such as digital calendars or to-do list apps can help you stay organized. It is also important to eliminate distractions in your work environment. Identify what distracts you, whether it\'s smartphone notifications, social media, or ambient noise, and find ways to minimize them to stay focused on your tasks. Don\'t forget to take regular breaks. Working non-stop is not the key to productivity, but working smart is. Regular breaks help recharge your mental batteries. The Pomodoro technique, which involves working intensely for 25 minutes, then taking a 5-minute break, is an excellent strategy to adopt. Adopting healthy habits can also improve your concentration and energy. Make sure to eat well, hydrate properly, and engage in regular physical activity. Good sleep and effective stress management are also essential for maintaining optimal performance. Finally, learn to delegate some tasks. Recognize that you can\'t do everything alone. By entrusting certain responsibilities to colleagues or using external services, you can focus on what really matters. By integrating these practices into your daily routine, you can not only optimize your efficiency but also achieve your goals more quickly and satisfactorily. Remember that productivity is a journey, not a destination. Continue to adjust and refine your methods to find what works best for you.',
        publication_date=date(2024, 6, 28)
    )
    article1.save()

    article2 = Article(
        title='Top Technological Trends to Watch in 2025',
        content='Dive into the world of emerging innovations that promise to redefine the technology industry in the years to come. At the dawn of a new era, technological advancements are multiplying at a rapid pace, transforming our daily lives and opening new possibilities for the future. Cutting-edge technologies such as artificial intelligence, the Internet of Things (IoT), and 5G are disrupting traditional sectors, bringing innovative solutions to global challenges. Artificial intelligence continues to improve, offering increasingly sophisticated applications ranging from personal virtual assistants to advanced medical diagnostics. IoT, meanwhile, is connecting more devices every day, creating an interconnected ecosystem where data flows smoothly and instantaneously, optimizing industrial processes and enhancing individuals\' quality of life. 5G, with its promise of ultra-fast connection speeds and reduced latency, is paving the way for new possibilities in areas such as autonomous vehicles, augmented reality, and smart cities. Concurrently, emerging technologies such as blockchain, virtual reality, and biotechnology are beginning to make their mark, offering innovations that could revolutionize how we interact with the world. These innovations are not only transforming products and services but also reshaping business models and strategies, requiring companies to adapt quickly to remain competitive. Technology startups play a crucial role in this ever-changing landscape, developing disruptive solutions that push the boundaries of what is possible. Exploring these emerging innovations helps understand how they will redefine the technology industry and impact our lives. By staying informed about current and future trends, you can anticipate changes and seize the opportunities they present, whether as a professional, investor, or technology enthusiast.',
        publication_date=date(2024, 6, 28)
    )
    article2.save()

    article3 = Article(
        title='Tips for Succeeding in a Job Interview',
        content='Discover practical tips to stand out to recruiters and land the job of your dreams. Job hunting can be challenging, but with the right strategies, you can not only attract employers\' attention but also convince them that you are the ideal candidate. It all starts with preparation. Make sure your resume is up to date, well-structured, and highlights your relevant skills and experiences. Use relevant keywords for the industry you are applying for to pass through applicant tracking system filters. Next, customize your cover letter for each position. Explain why you are interested in the role and how your skills and experiences qualify you for it. Research the company to show that you understand its goals and culture, and explain how you can contribute to its success. Confidence and preparation are essential during interviews. Practice your answers to common questions and prepare concrete examples of your past achievements. Show your enthusiasm for the position and the company, and don\'t hesitate to ask relevant questions that demonstrate your interest and thoughtful consideration of the role. Body language is also important: maintain eye contact, adopt an open posture, and use gestures to reinforce your speech. Be attentive and actively listen to what the interviewer is saying. After the interview, don\'t forget to thank the recruiters for their time with a follow-up email. Reiterate your interest in the position and mention one or two points discussed during the interview that particularly appealed to you. This demonstrates your professionalism and seriousness. By following these practical tips, you will increase your chances of impressing recruiters and landing your next job. Preparation, customization, and effective communication are the keys to standing out in a competitive job market.',
        publication_date=date(2024, 6, 28)
    )
    article3.save()

    article4 = Article(
        title='How to Start a Startup in 2024',
        content='Launching a successful business in today\'s economic climate requires a strategic and well-planned approach. The first essential step is to clearly define your business idea. Identify a niche or unmet need in the market and develop an innovative product or service that addresses it. Conduct thorough research to understand your target market, competition, and current trends. This will enable you to refine your unique value proposition and stand out. Next, develop a solid business plan. This document will serve as a roadmap for your business and is crucial for attracting investors. It should include a detailed market analysis, marketing strategy, operational plan, and realistic financial projections. Ensure your plan is flexible to adapt to economic changes and new opportunities. Building a competent team is also essential. Surround yourself with people who share your vision and possess complementary skills. A dynamic and talented team can make all the difference in your business\'s success. In terms of funding, explore various options such as venture capital, bank loans, or grants. Don\'t forget about crowdfunding, which can also be a viable solution. Be prepared to present your project convincingly to potential investors and demonstrate your business\'s viability. Implementing an effective marketing strategy is crucial for attracting and retaining customers. Use digital marketing channels such as social media, search engine optimization (SEO), and email marketing to reach your target audience. Create an attractive and user-friendly website that showcases your products or services. Lastly, be adaptable and ready to innovate constantly. The economic climate can be unpredictable, and flexibility is essential for navigating challenges. Stay tuned to customer feedback and market trends to adjust your offering accordingly. By following these essential steps, you will increase your chances of launching a successful business in today\'s economic climate. The key is meticulous preparation, precise execution, and a constant ability to adapt to changes and opportunities.',
        publication_date=date(2024, 6, 28)
    )
    article4.save()

    article5 = Article(
        title='Complete Beginner\'s Guide to Web Development',
        content='Learning the basics of coding is an essential skill in today\'s digital world. If you\'re a beginner, it\'s important to start by understanding the fundamental principles of programming. Programming languages such as HTML, CSS, and JavaScript are ideal starting points. HTML (HyperText Markup Language) is used to structure the content of a web page, CSS (Cascading Style Sheets) to style and format that content, and JavaScript to add dynamic interactions. Start with free online tutorials or interactive courses that will guide you step-by-step through the basics. Platforms like Codecademy, freeCodeCamp, or W3Schools offer excellent resources for beginners. By following these courses, you\'ll learn how to create simple web pages and understand how different web technologies work together. Once you have a basic understanding, put your knowledge into practice by building your first website. Choose a simple project, such as a personal portfolio or blog, and start coding. Use HTML to create the structure of your site, CSS to define its appearance, and JavaScript to add interactive features. It\'s also helpful to familiarize yourself with web development tools like code editors (Visual Studio Code, Sublime Text) and version control systems (Git). These tools will help you write, organize, and manage your code efficiently. Don\'t be afraid to make mistakes and seek solutions to the problems you encounter. Programming is a continuous learning process, and each project will help improve your skills. Participate in discussion forums, join developer communities, and ask for help when you need it. Sites like Stack Overflow can be valuable resources for finding answers to your technical questions. By committing to regular learning and practicing your coding skills, you\'ll soon be able to create functional and attractive websites. Start today and discover the joy and satisfaction of seeing your ideas come to life through code.',
        publication_date=date(2024, 6, 28)
    )
    article5.save()

    article6 = Article(
        title='Top Travel Destinations for This Summer',
        content='Summer is the ideal season to explore dream destinations and relax away from the everyday hustle and bustle. Discover beautiful places to visit during the summer season and fully enjoy your vacation. Whether you\'re looking for paradise beaches, majestic mountains, or historic cities, there\'s a destination for every type of traveler. For beach lovers, the Greek islands like Santorini and Mykonos offer breathtaking landscapes with crystal-clear waters and charming white villages. In Spain, the Costa Brava offers secluded coves and golden sandy beaches, perfect for sunbathing. Nature and hiking enthusiasts can head to the Swiss or French Alps, where mountain trails offer panoramic views and fresh air. American national parks like Yosemite or Yellowstone are also popular choices, with varied landscapes ranging from lush forests to spectacular geysers. For a cultural getaway, explore Europe\'s historic cities. Rome, with its ancient monuments and picturesque alleys, or Paris, the city of love with its renowned museums and charming cafes, are must-visit destinations. Prague and Budapest also offer rich history and magnificent architecture to explore. Finally, for those seeking an exotic adventure, Southeast Asia is full of fascinating destinations. Bali, with its idyllic beaches and unique culture, or Vietnam, with its diverse landscapes and culinary delights, are perfect choices for a memorable trip. No matter your destination, don\'t forget to plan ahead to make the most of your stay. Book your accommodations, check local health conditions, and prepare a list of activities to do on site. By organizing well, you can ensure a stress-free and truly relaxing vacation. Explore these beautiful places, immerse yourself in new cultures, and create unforgettable memories during the summer season. Enjoy every moment and be captivated by the beauty of the world around you.',
        publication_date=date(2024, 6, 28)
    )
    article6.save()

if _name_ == '_main_':
    add_articles()
    print("Articles ajoutés avec succès !")