# Generated by Django 3.2.25 on 2024-06-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20240628_0052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='language',
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
